### ISSUE TITLE
Unable to see metrics

### ISSUE THREAD

**Issue by gmaharram** [lesovsky/pgscv#36]
I have configured pgscv using following link: https://github.com/lesovsky/pgscv/wiki/Setup-for-regular-users
But, I cannot get metrics like lock and waits, or wal. Also I get zero when i run this command
 curl -s http://127.0.0.1:9890/metrics | grep -c ^postgres

**Comment by lesovsky** [comment]
Check pgscv logs, seems it doesn't connect to Postgres

**Comment by gmaharram** [comment]
Thank you! It works now, but i cannot see metrics like errors, logs, replication. Logging_collector is on, and I got this error
in grafana related to pg_stat_statements. Pg_stat_statements is also enabled.

"found duplicate series for the match group {database=\"postgres\", user=\"postgres\"} on the right hand-side of the operation: [{database=\"postgres\", instance=\":9890\", job=\"pgscv_postgres\", , query=\"SELECT c1.relnamespace::regnamespace::text AS schema, c1.relname AS table, a1.attname||?||t1.typname AS column, c2.relnamespace::regnamespace::text AS refschema, c2.relname AS reftable, a2.attname||?||t2.typname AS refcolumn FROM pg_constraint JOIN pg_class c1 ON c1.oid = conrelid JOIN pg_class c2 ON c2.oid = confrelid JOIN pg_attribute a1 ON a1.attnum = conkey[?] AND a1.attrelid = conrelid JOIN pg_attribute a2 ON a2.attnum = confkey[?] AND a2.attrelid = confrelid JOIN pg_type t1 ON t1.oid = a1.atttypid JOIN pg_type t2 ON t2.oid = a2.atttypid WHERE a1.atttypid <> a2.atttypid AND contype = ?\", service_id=\"postgres:5432\", user=\"postgres\"}, {database=\"postgres\", instance=\"10.0.90.14:9890\", job=\"pgscv_postgres\", query=\"SELECT extract(? FROM pg_postmaster_start_time())\", service_id=\"postgres:5432\", user=\"postgres\"}];many-to-many matching not allowed: matching labels must be unique on one side"
