### ISSUE TITLE
Prometheus data source error

### ISSUE THREAD

**Issue by Serg-cl** [lesovsky/pgscv#42]
Метрика доступна по url http://xx.xx.xx.xxx:9890/metrics в браузере, однако при добавлении 
в grafana получаю всегда такую ошибку! Подскажите в чем может быть дело ? версия Grafana v9.0.2 (0641b5d0cd)

_Error reading Prometheus: bad_response: readObjectStart: expect { or n, but found <, error found in #1 byte of ...|<html> <hea|..., bigger context ...|<html> <head><title>pgSCV / Weaponry metrics collec|..._

Так же каждый запрос с дашбордов возвращает :

**request:Object
url:"api/datasources/proxy/6/api/v1/query_range?query=100%20*%20sum%20by%20(mode)%20(rate(node_cpu_seconds_total%7Bmode!%3D%22idle%22%2Cinstance%3D%22%22%7D%5B1m%5D))%20%2F%20on%20(instance)%20group_left%20sum(rate(node_cpu_seconds_all_total%7Binstance%3D%22%22%7D%5B1m%5D))&start=1657528035&end=1657549635&step=15"
method:"GET"
hideFromInspector:false
response:"<html>
<head><title>pgSCV / Weaponry metrics collector</title></head>
<body>
pgSCV / <a href="https://weaponry.io">Weaponry</a> metrics collector, for more info visit <a href="https://github.com/weaponry/pgscv">Github</a> page.
<p><a href="/metrics">Metrics</a></p>
</body>
</html>
"**

**Comment by lesovsky** [comment]
Recreate the issue using the following [template](https://github.com/lesovsky/pgscv/issues/new?assignees=&labels=&template=bug_report.md&title=) and English please.

Also post the link to the dashboard.
